id: IBF393A4F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T10:54:15+00:00'
last_modified: '2022-06-07T15:03:54.581884+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG21231
  title: རྩོམ་རིག་རྣམ་བཤད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    5FE6:
      image_group_id: I1KG21307
      title: ''
      total_pages: 602
      order: 1
      base_file: 5FE6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
