id: P001763
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:19:59.488007
source_metadata:
  id: bdr:W1KG21231
  title: རྩོམ་རིག་རྣམ་བཤད།
  author: ''
  volumes:
    58124d3c1f0a4dc4aac01ef581291c58:
      image_group_id: I1KG21307
      title: ''
      volume_number: 1
      total_pages: 602
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
